# Generated by Django 3.1.7 on 2021-06-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='country',
        ),
    ]
