# Generated by Django 3.1.7 on 2021-04-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0002_nationality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
