# Generated by Django 3.1.7 on 2021-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=224),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=224),
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=224),
        ),
    ]
