# Generated by Django 3.1.7 on 2021-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='country',
            field=models.ManyToManyField(blank=True, to='localize.Country'),
        ),
    ]
