# Generated by Django 3.1.7 on 2021-07-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sku_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
