# Generated by Django 3.1.7 on 2021-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210603_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='category',
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=224, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=224, unique=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
