# Generated by Django 3.1.7 on 2021-07-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('product', '0003_remove_brand_category'),
        ('localize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMonitorSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('date', models.DateField()),
                ('sku', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('mode', models.FloatField()),
                ('mean', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.channel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localize.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
