# Generated by Django 3.1.7 on 2021-07-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_brand_category'),
        ('snap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemonitorsnap',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='pricemonitorsnap',
            name='category',
        ),
        migrations.AlterField(
            model_name='pricemonitorsnap',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sku'),
        ),
    ]
