# Generated by Django 3.1.7 on 2021-08-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_brand_category'),
        ('localize', '0001_initial'),
        ('market', '0001_initial'),
        ('snap', '0002_auto_20210728_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfStockSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('not_available_in_month', models.FloatField()),
                ('less_available_in_month', models.FloatField()),
                ('available_in_month', models.FloatField()),
                ('not_available_by_store', models.FloatField()),
                ('less_available_by_store', models.FloatField()),
                ('available_by_store', models.FloatField()),
                ('not_available_by_city', models.FloatField()),
                ('less_available_by_city', models.FloatField()),
                ('available_by_city', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localize.city')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sku')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
