# Generated by Django 3.1.7 on 2021-08-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0001_initial'),
        ('market', '0001_initial'),
        ('product', '0003_remove_brand_category'),
        ('question', '0002_auto_20210701_1801'),
        ('snap', '0003_outofstocksnap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('question_statement', models.CharField(max_length=250)),
                ('total_yes', models.FloatField(blank=True, null=True)),
                ('total_no', models.FloatField(blank=True, null=True)),
                ('rating_one_on_three', models.FloatField(blank=True, null=True)),
                ('rating_two_on_three', models.FloatField(blank=True, null=True)),
                ('rating_three_on_three', models.FloatField(blank=True, null=True)),
                ('rating_one_on_five', models.FloatField(blank=True, null=True)),
                ('rating_two_on_five', models.FloatField(blank=True, null=True)),
                ('rating_three_on_five', models.FloatField(blank=True, null=True)),
                ('rating_four_on_five', models.FloatField(blank=True, null=True)),
                ('rating_five_on_five', models.FloatField(blank=True, null=True)),
                ('rating_one_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_two_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_three_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_four_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_five_of_ten', models.FloatField(blank=True, null=True)),
                ('rating_six_of_ten', models.FloatField(blank=True, null=True)),
                ('rating_seven_of_ten', models.FloatField(blank=True, null=True)),
                ('rating_eight_of_ten', models.FloatField(blank=True, null=True)),
                ('rating_nine_of_ten', models.FloatField(blank=True, null=True)),
                ('rating_ten_of_ten', models.FloatField(blank=True, null=True)),
                ('average_numeric', models.FloatField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.channel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localize.city')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questiontype')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sku')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
