# Generated by Django 3.1.7 on 2021-08-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0004_consumersnap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumersnap',
            old_name='rating_eight_of_ten',
            new_name='rating_eight_on_ten',
        ),
        migrations.RenameField(
            model_name='consumersnap',
            old_name='rating_five_of_ten',
            new_name='rating_five_on_ten',
        ),
        migrations.RenameField(
            model_name='consumersnap',
            old_name='rating_nine_of_ten',
            new_name='rating_nine_on_ten',
        ),
        migrations.RenameField(
            model_name='consumersnap',
            old_name='rating_seven_of_ten',
            new_name='rating_seven_on_ten',
        ),
        migrations.RenameField(
            model_name='consumersnap',
            old_name='rating_six_of_ten',
            new_name='rating_six_on_ten',
        ),
        migrations.RenameField(
            model_name='consumersnap',
            old_name='rating_ten_of_ten',
            new_name='rating_ten_on_ten',
        ),
    ]
