# Generated by Django 3.1.7 on 2021-08-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_brand_category'),
        ('market', '0001_initial'),
        ('localize', '0001_initial'),
        ('snap', '0005_auto_20210805_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('sku_by_country', models.FloatField(blank=True, null=True)),
                ('sku_by_channel', models.FloatField(blank=True, null=True)),
                ('brand_by_city', models.FloatField(blank=True, null=True)),
                ('brand_by_country', models.FloatField(blank=True, null=True)),
                ('share_brand_by_country', models.FloatField(blank=True, null=True)),
                ('share_brand_by_channel', models.FloatField(blank=True, null=True)),
                ('share_sku_by_channel', models.FloatField(blank=True, null=True)),
                ('share_sku_by_country', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localize.city')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sku')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
