# Generated by Django 3.1.7 on 2021-08-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0006_distributionsnap'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionsnap',
            name='sku_by_city',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
