# Generated by Django 3.1.7 on 2021-08-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0008_snapbrand_snapcategory_snapchannel_snapretailer_snapsku_snapstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumersnap',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='consumersnap',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='store',
        ),
        migrations.RemoveField(
            model_name='outofstocksnap',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='outofstocksnap',
            name='store',
        ),
        migrations.RemoveField(
            model_name='pricemonitorsnap',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='pricemonitorsnap',
            name='sku',
        ),
    ]
