# Generated by Django 3.1.7 on 2021-08-19 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0009_auto_20210819_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumersnap',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapchannel'),
        ),
        migrations.AddField(
            model_name='consumersnap',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapsku'),
        ),
        migrations.AddField(
            model_name='distributionsnap',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapsku'),
        ),
        migrations.AddField(
            model_name='distributionsnap',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapstore'),
        ),
        migrations.AddField(
            model_name='outofstocksnap',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapsku'),
        ),
        migrations.AddField(
            model_name='outofstocksnap',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapstore'),
        ),
        migrations.AddField(
            model_name='pricemonitorsnap',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapchannel'),
        ),
        migrations.AddField(
            model_name='pricemonitorsnap',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapsku'),
        ),
    ]
