# Generated by Django 3.1.7 on 2021-08-25 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0010_auto_20210819_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionsnap',
            name='brand_by_city',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='brand_by_country',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='share_brand_by_channel',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='share_brand_by_country',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='share_sku_by_channel',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='share_sku_by_country',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='sku_by_country',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='store',
        ),
    ]
