# Generated by Django 3.1.7 on 2021-08-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0011_auto_20210825_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionsnap',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapchannel'),
        ),
    ]
