# Generated by Django 3.1.7 on 2021-09-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0012_distributionsnap_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributionsnap',
            old_name='sku_by_channel',
            new_name='total_distribution',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='count',
        ),
        migrations.RemoveField(
            model_name='distributionsnap',
            name='sku_by_city',
        ),
    ]
