# Generated by Django 3.1.7 on 2021-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0013_auto_20210906_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionsnap',
            name='number_of_outlet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionsnap',
            name='shelf_share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
