# Generated by Django 3.1.7 on 2022-04-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0014_auto_20210909_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnapCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snap.snapcountry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consumersnap',
            name='snap_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapcity'),
        ),
        migrations.AddField(
            model_name='distributionsnap',
            name='snap_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapcity'),
        ),
        migrations.AddField(
            model_name='outofstocksnap',
            name='snap_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapcity'),
        ),
        migrations.AddField(
            model_name='pricemonitorsnap',
            name='snap_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapcity'),
        ),
        migrations.AddField(
            model_name='snapstore',
            name='snap_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapcity'),
        ),
    ]
