# Generated by Django 3.1.7 on 2022-04-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0015_auto_20220410_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapPriceMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('date', models.DateField(db_index=True)),
                ('city_id', models.BigIntegerField(db_index=True)),
                ('city_name', models.CharField(db_index=True, max_length=255)),
                ('country_id', models.BigIntegerField(db_index=True)),
                ('country_name', models.CharField(db_index=True, max_length=255)),
                ('channel_id', models.BigIntegerField(db_index=True)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('category_id', models.BigIntegerField(db_index=True)),
                ('category_name', models.CharField(db_index=True, max_length=255)),
                ('brand_id', models.BigIntegerField(db_index=True)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('sku_id', models.BigIntegerField(db_index=True)),
                ('sku_name', models.CharField(db_index=True, max_length=255)),
                ('count', models.IntegerField()),
                ('mode', models.FloatField()),
                ('mean', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
