# Generated by Django 3.1.7 on 2022-04-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0016_snappricemonitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapsku',
            name='country',
        ),
    ]
