# Generated by Django 3.1.7 on 2022-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0018_auto_20220418_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('date', models.DateField()),
                ('ity_id', models.BigIntegerField(db_index=True)),
                ('city_name', models.CharField(db_index=True, max_length=255)),
                ('country_id', models.BigIntegerField(db_index=True)),
                ('country_name', models.CharField(db_index=True, max_length=255)),
                ('channel_id', models.BigIntegerField(db_index=True)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('category_id', models.BigIntegerField(db_index=True)),
                ('category_name', models.CharField(db_index=True, max_length=255)),
                ('brand_id', models.BigIntegerField(db_index=True)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('sku_id', models.BigIntegerField(db_index=True)),
                ('sku_name', models.CharField(db_index=True, max_length=255)),
                ('total_distribution', models.FloatField(blank=True, null=True)),
                ('shelf_share', models.FloatField(blank=True, null=True)),
                ('number_of_outlet', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnapOutOfStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('date', models.DateField()),
                ('city_id', models.BigIntegerField(db_index=True)),
                ('city_name', models.CharField(db_index=True, max_length=255)),
                ('country_id', models.BigIntegerField(db_index=True)),
                ('country_name', models.CharField(db_index=True, max_length=255)),
                ('channel_id', models.BigIntegerField(db_index=True)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('retailer_id', models.BigIntegerField(db_index=True)),
                ('retailer_name', models.CharField(db_index=True, max_length=255)),
                ('store_id', models.BigIntegerField(db_index=True)),
                ('store_name', models.CharField(db_index=True, max_length=255)),
                ('category_id', models.BigIntegerField(db_index=True)),
                ('category_name', models.CharField(db_index=True, max_length=255)),
                ('brand_id', models.BigIntegerField(db_index=True)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('sku_id', models.BigIntegerField(db_index=True)),
                ('sku_name', models.CharField(db_index=True, max_length=255)),
                ('count', models.IntegerField()),
                ('not_available_in_month', models.FloatField()),
                ('less_available_in_month', models.FloatField()),
                ('available_in_month', models.FloatField()),
                ('not_available_by_store', models.FloatField()),
                ('less_available_by_store', models.FloatField()),
                ('available_by_store', models.FloatField()),
                ('not_available_by_city', models.FloatField()),
                ('less_available_by_city', models.FloatField()),
                ('available_by_city', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='outofstocksnap',
            name='city',
        ),
        migrations.RemoveField(
            model_name='outofstocksnap',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='outofstocksnap',
            name='snap_city',
        ),
        migrations.RemoveField(
            model_name='outofstocksnap',
            name='store',
        ),
        migrations.RemoveField(
            model_name='pricemonitorsnap',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='pricemonitorsnap',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pricemonitorsnap',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='pricemonitorsnap',
            name='snap_city',
        ),
        migrations.DeleteModel(
            name='DistributionSnap',
        ),
        migrations.DeleteModel(
            name='OutOfStockSnap',
        ),
        migrations.DeleteModel(
            name='PriceMonitorSnap',
        ),
    ]
