# Generated by Django 3.1.7 on 2022-04-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0019_auto_20220424_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapdistribution',
            old_name='ity_id',
            new_name='city_id',
        ),
    ]
