# Generated by Django 3.1.7 on 2022-05-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0020_auto_20220425_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapstore',
            name='snap_city',
        ),
        migrations.AlterField(
            model_name='snapstore',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap.snapcity'),
        ),
    ]
