# Generated by Django 3.1.7 on 2022-05-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210701_1801'),
        ('snap', '0021_auto_20220521_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('date', models.DateField()),
                ('city_id', models.BigIntegerField(db_index=True)),
                ('city_name', models.CharField(db_index=True, max_length=255)),
                ('country_id', models.BigIntegerField(db_index=True)),
                ('country_name', models.CharField(db_index=True, max_length=255)),
                ('channel_id', models.BigIntegerField(db_index=True)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('category_id', models.BigIntegerField(db_index=True)),
                ('category_name', models.CharField(db_index=True, max_length=255)),
                ('brand_id', models.BigIntegerField(db_index=True)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('sku_id', models.BigIntegerField(db_index=True)),
                ('sku_name', models.CharField(db_index=True, max_length=255)),
                ('count', models.IntegerField()),
                ('question_statement', models.CharField(max_length=250)),
                ('total_yes', models.FloatField(blank=True, null=True)),
                ('total_no', models.FloatField(blank=True, null=True)),
                ('rating_one_on_three', models.FloatField(blank=True, null=True)),
                ('rating_two_on_three', models.FloatField(blank=True, null=True)),
                ('rating_three_on_three', models.FloatField(blank=True, null=True)),
                ('rating_one_on_five', models.FloatField(blank=True, null=True)),
                ('rating_two_on_five', models.FloatField(blank=True, null=True)),
                ('rating_three_on_five', models.FloatField(blank=True, null=True)),
                ('rating_four_on_five', models.FloatField(blank=True, null=True)),
                ('rating_five_on_five', models.FloatField(blank=True, null=True)),
                ('rating_one_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_two_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_three_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_four_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_five_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_six_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_seven_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_eight_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_nine_on_ten', models.FloatField(blank=True, null=True)),
                ('rating_ten_on_ten', models.FloatField(blank=True, null=True)),
                ('average_numeric', models.FloatField(blank=True, null=True)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ConsumerSnap',
        ),
    ]
