# Generated by Django 3.1.7 on 2021-06-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0002_remove_area_country'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='country',
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localize.city'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
