# Generated by Django 3.1.7 on 2021-06-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210617_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.channel'),
        ),
    ]
