# Generated by Django 3.1.7 on 2021-04-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0001_initial'),
        ('market', '0002_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.channel'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localize.city'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localize.country'),
        ),
    ]
