# Generated by Django 3.1.7 on 2021-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210603_0957'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('name', 'retailer', 'city'), name='unique_store'),
        ),
    ]
