# Generated by Django 3.1.7 on 2021-04-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent_user',
            field=models.BooleanField(default=False, help_text='Designates whether this user is agent or not. Unselect this if user is not a agent.', verbose_name='agent user'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_portal_user',
            field=models.BooleanField(default=False, help_text='Designates whether this user is portal user or not. Unselect this if user is not a portal user.', verbose_name='portal user'),
        ),
    ]
