# Generated by Django 3.1.7 on 2021-05-09 10:16

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=apps.core.fields.PhoneNumberField(max_length=10, null=True),
        ),
    ]
