# Generated by Django 3.1.7 on 2021-04-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210423_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuser',
            name='total_completed_questionnaire',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
