# Generated by Django 3.1.7 on 2021-05-16 15:51

import apps.user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=apps.user.utils.upload_avatar_to),
        ),
    ]
