# Generated by Django 3.1.7 on 2021-04-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0002_nationality'),
        ('user', '0003_agentuser_total_completed_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localize.nationality'),
        ),
    ]
