# Generated by Django 3.1.7 on 2021-04-23 10:03

import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[apps.user.validators.DateOfBirthValidator()]),
        ),
    ]
