# Generated by Django 3.1.7 on 2021-05-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0001_initial'),
        ('user', '0004_auto_20210516_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localize.country'),
        ),
    ]
