# Generated by Django 3.1.7 on 2021-05-17 16:01

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210517_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=apps.core.fields.PhoneNumberField(max_length=20, null=True),
        ),
    ]
