# Generated by Django 3.1.7 on 2021-05-20 13:35

import apps.user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210517_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.png', upload_to=apps.user.utils.upload_avatar_to),
        ),
    ]
