# Generated by Django 3.1.7 on 2021-05-20 14:59

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0001_initial'),
        ('user', '0007_auto_20210520_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=apps.core.fields.PhoneNumberField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localize.country'),
        ),
    ]
