# Generated by Django 3.1.7 on 2021-05-27 13:09

import apps.core.validators
import apps.user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210520_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.png', upload_to=apps.user.utils.upload_avatar_to, validators=[apps.core.validators.ImageValidator()]),
        ),
    ]
