# Generated by Django 3.1.7 on 2021-06-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210527_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuser',
            name='total_completed_questionnaire',
        ),
    ]
