# Generated by Django 3.1.7 on 2021-04-25 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('question', '0001_initial'),
        ('questionnaire', '0001_initial'),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='response.response'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='agent',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='user.agentuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='questionnaire',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
            preserve_default=False,
        ),
    ]
