# Generated by Django 3.1.7 on 2021-07-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('response', '0001_initial'),
        ('questionnaire', '0002_questionnaire_tags'),
        ('user', '0001_initial'),
        ('question', '0002_auto_20210701_1801'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecycle',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agentuser'),
        ),
        migrations.AddField(
            model_name='responsecycle',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='response',
            name='response_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='response.responsecycle'),
        ),
        migrations.AddField(
            model_name='response',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.store'),
        ),
        migrations.AddField(
            model_name='optionanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.answer'),
        ),
        migrations.AddField(
            model_name='optionanswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionoption'),
        ),
        migrations.AddField(
            model_name='numericanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='response.answer'),
        ),
        migrations.AddField(
            model_name='imageanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.answer'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='response.answer'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questiontypechoice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.response'),
        ),
    ]
