# Generated by Django 3.1.7 on 2021-05-11 12:41

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('response', '0003_auto_20210511_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='latitude',
            field=apps.core.fields.LatitudeField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='longitude',
            field=apps.core.fields.LongitudeField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.retailer'),
        ),
    ]
