# Generated by Django 3.1.7 on 2021-05-17 20:47

import apps.response.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210517_2047'),
        ('response', '0004_auto_20210511_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='imageanswer',
            name='image',
            field=models.ImageField(upload_to=apps.response.utils.upload_answer_image_to),
        ),
        migrations.AddConstraint(
            model_name='optionanswer',
            constraint=models.UniqueConstraint(fields=('answer', 'option'), name='unique_option_answer'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='response.answer'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questiontypechoice'),
        ),
    ]
