# Generated by Django 3.1.7 on 2021-05-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_auto_20210517_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
