# Generated by Django 3.1.7 on 2021-05-17 23:17

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_response_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='latitude',
            field=apps.core.fields.LatitudeField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='longitude',
            field=apps.core.fields.LongitudeField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
