# Generated by Django 3.1.7 on 2021-05-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_auto_20210517_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completed_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
