# Generated by Django 3.1.7 on 2021-05-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0008_response_completed_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('numeric', models.FloatField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='response.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('text', models.CharField(max_length=255)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='response.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='InputAnswer',
        ),
    ]
