# Generated by Django 3.1.7 on 2021-05-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0009_auto_20210527_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='completed_date_time',
            new_name='completed_at',
        ),
    ]
