# Generated by Django 3.1.7 on 2021-05-30 16:17

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0010_auto_20210528_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[apps.core.validators.LatitudeValidator()]),
        ),
        migrations.AlterField(
            model_name='response',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[apps.core.validators.LongitudeValidator()]),
        ),
    ]
