# Generated by Django 3.1.7 on 2021-06-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210603_0957'),
        ('response', '0011_auto_20210530_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='retailer',
        ),
        migrations.AddField(
            model_name='response',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.store'),
        ),
    ]
