# Generated by Django 3.1.7 on 2021-06-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20210603_1348'),
        ('user', '0009_auto_20210527_1309'),
        ('response', '0012_auto_20210603_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='response',
            name='questionnaire',
        ),
        migrations.CreateModel(
            name='ResponseCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agentuser')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='response',
            name='response_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='response.responsecycle'),
        ),
    ]
