# Generated by Django 3.1.7 on 2021-06-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0013_auto_20210614_0900'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('response_cycle', 'store'), name='unique_response'),
        ),
        migrations.AddConstraint(
            model_name='responsecycle',
            constraint=models.UniqueConstraint(fields=('agent', 'questionnaire', 'is_completed'), name='unique_response_cycle'),
        ),
    ]
