# Generated by Django 3.1.7 on 2021-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0014_auto_20210614_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
