# Generated by Django 3.1.7 on 2021-06-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0015_response_started_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='responsecycle',
            name='unique_response_cycle',
        ),
    ]
