# Generated by Django 3.1.7 on 2021-04-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontype',
            old_name='type',
            new_name='name',
        ),
    ]
