# Generated by Django 3.1.7 on 2021-06-16 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('question', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='question',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sku'),
        ),
        migrations.AddConstraint(
            model_name='questiontypechoice',
            constraint=models.UniqueConstraint(fields=('question_type', 'choice'), name='unique_question_type_choice'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'option'), name='unique_question_option'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'statement'), name='unique_question'),
        ),
    ]
