# Generated by Django 3.1.7 on 2021-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210419_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.CharField(max_length=244),
        ),
        migrations.AlterField(
            model_name='questionstatement',
            name='statement',
            field=models.CharField(max_length=244),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(max_length=244),
        ),
    ]
