# Generated by Django 3.1.7 on 2021-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_statement',
        ),
        migrations.AddField(
            model_name='question',
            name='statement',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
