# Generated by Django 3.1.7 on 2021-05-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210504_2001'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'statement'), name='unique_question'),
        ),
    ]
