# Generated by Django 3.1.7 on 2021-05-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20210509_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='questiontype',
            name='has_default_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'option'), name='unique_question_option'),
        ),
        migrations.AddField(
            model_name='questiontypechoice',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questiontype'),
        ),
        migrations.AddConstraint(
            model_name='questiontypechoice',
            constraint=models.UniqueConstraint(fields=('question_type', 'choice'), name='unique_question_type_choice'),
        ),
    ]
