# Generated by Django 3.1.7 on 2021-05-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210517_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(limit_choices_to={'question_type__has_options': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
