# Generated by Django 3.1.7 on 2021-06-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20210519_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionStatement',
        ),
        migrations.RemoveField(
            model_name='question',
            name='brand',
        ),
    ]
