# Generated by Django 3.1.7 on 2021-06-16 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('localize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('can_repeat', models.BooleanField(default=False)),
                ('repeat_cycle', models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Repeat Cycle in week, ex: 1 week , 2 week and so on.', null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('city', models.ManyToManyField(to='localize.City')),
                ('questionnaire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnairetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
