# Generated by Django 3.1.7 on 2021-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.AgentUser'),
        ),
    ]
