# Generated by Django 3.1.7 on 2021-07-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.AgentUser'),
        ),
    ]
