# Generated by Django 3.1.7 on 2021-05-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20210504_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='repeat_cycle',
        ),
    ]
