# Generated by Django 3.1.7 on 2021-05-23 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20210523_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='repeat_cycle',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Repeat Cycle in week, ex: 1 week , 2 week and so on.', null=True),
        ),
    ]
