# Generated by Django 3.1.7 on 2021-05-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20210523_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='can_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='repeat_cycle',
            field=models.DurationField(blank=True, help_text='Repeat Cycle in week, ex: 1 week , 2 week and so on.', null=True),
        ),
    ]
