# Generated by Django 3.1.7 on 2021-06-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20210523_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='country',
        ),
    ]
