# Generated by Django 3.1.7 on 2021-06-03 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_remove_questionnaire_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='repeat_cycle',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Repeat Cycle in week, ex: 1 week , 2 week and so on.', null=True),
        ),
    ]
