# Generated by Django 3.1.7 on 2021-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20210603_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='questionnairetype',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
