from django.urls import path, include

urlpatterns = [
    path(
        'price-monitor/',
        include('apps.snap.urls.price_monitor_urls')
    ),
    path(
        'out-of-stock/',
        include('apps.snap.urls.out_of_stock_urls')
    ),
    path(
        'consumer/',
        include('apps.snap.urls.consumer_urls')
    ),
    path(
        'distribution/',
        include('apps.snap.urls.distribution_urls')
    ),
    # ----operations----
    path(
        'snap-category/',
        include('apps.snap.urls.category_urls')
    ),
    path(
        'snap-brand/',
        include('apps.snap.urls.brand_urls')
    ),
    path(
        'snap-sku/',
        include('apps.snap.urls.sku_urls')
    ),
    path(
        'snap-channel/',
        include('apps.snap.urls.channel_urls')
    ),
    path(
        'snap-retailer/',
        include('apps.snap.urls.retailer_urls')
    ),
    path(
        'snap-store/',
        include('apps.snap.urls.store_urls')
    ),
    path(
        'snap-country/',
        include('apps.snap.urls.country_urls')
    ),
    path(
        'snap-city/',
        include('apps.snap.urls.city_urls')
    ),
    path(
        'filters/',
        include('apps.snap.urls.filters_urls')
    ),
]
