from django.urls import path, include

from apps.snap.views import price_monitor_views

report_urls = [
    path(
        'overview',
        price_monitor_views.OverviewPriceMonitorSnapReportView.as_view(),
        name='overview-price-monitor-snap-report'
    ),
    path(
        'month-max',
        price_monitor_views.MonthMaxPriceMonitorSnapReportView.as_view(),
        name='month-max-price-monitor-snap-report'
    ),
    path(
        'month-min',
        price_monitor_views.MonthMinPriceMonitorSnapReportView.as_view(),
        name='month-min-price-monitor-snap-report'
    ),
    path(
        'month-mode',
        price_monitor_views.MonthModePriceMonitorSnapReportView.as_view(),
        name='month-mode-price-monitor-snap-report'
    ),
    path(
        'month-mean',
        price_monitor_views.MonthMeanPriceMonitorSnapReportView.as_view(),
        name='month-mean-price-monitor-snap-report'
    ),
    path(
        'brand-overview',
        price_monitor_views.BrandOverviewPriceMonitorSnapReportView.as_view(),
        name='brand-overview-price-monitor-snap-report'
    ),
    path(
        'country-min',
        price_monitor_views.CountryMinPriceMonitorSnapReportView.as_view(),
        name='country-min-price-monitor-snap-report'
    ),
    path(
        'country-max',
        price_monitor_views.CountryMaxPriceMonitorSnapReportView.as_view(),
        name='country-max-price-monitor-snap-report'
    ),
    path(
        'country-mean',
        price_monitor_views.CountryMeanPriceMonitorSnapReportView.as_view(),
        name='country-mean-price-monitor-snap-report'
    ),
    path(
        'country-mode',
        price_monitor_views.CountryModePriceMonitorSnapReportView.as_view(),
        name='country-mode-price-monitor-snap-report'
    ),
    path(
        'visit-per-city',
        price_monitor_views.VisitPerCityPriceMonitorSnapReportView.as_view(),
        name='visit-per-city-price-monitor-snap-report'
    ),
    path(
        'visit-per-country',
        price_monitor_views.VisitPerCountryPriceMonitorSnapReportView.as_view(),
        name='visit-per-country-price-monitor-snap-report'
    ),
    path(
        'sku-per-channel',
        price_monitor_views.SKUPerChannelPriceMonitorSnapReportView.as_view(),
        name='sku-per-channel-price-monitor-snap-report'
    )
]

urlpatterns = [
    path(
        'import',
        price_monitor_views.ImportPriceMonitorSnapView.as_view(),
        name='import-price-monitor-snap'
    ),
    path(
        'export',
        price_monitor_views.ExportPriceMonitorSnapView.as_view(),
        name='export-price-monitor-snap'
    ),
    path(
        'list',
        price_monitor_views.ListPriceMonitorSnapView.as_view(),
        name='list-price-monitor-snap'
    ),
    path(
        '<str:price_monitor_snap_id>/update',
        price_monitor_views.UpdatePriceMonitorSnapView.as_view(),
        name='update-price-monitor-snap'
    ),
    path(
        '<str:price_monitor_snap_id>/delete',
        price_monitor_views.DeletePriceMonitorSnapView.as_view(),
        name='delete-price-monitor-snap'
    ),
    path(
        'bulk-delete',
        price_monitor_views.BulkDeletePriceMonitorSnapView.as_view(),
        name='bulk-delete-price-monitor-snap'
    ),
    path(
        'month-list',
        price_monitor_views.ListPriceMonitorSnapMonthView.as_view(),
        name='list-price-monitor-snap-month'
    ),
    path(
        'report/',
        include(report_urls)
    ),
    path(
        'report/',
        include('apps.snap.urls.new_price_monitor_urls')
    )
]
