# Generated by Django 3.1.7 on 2021-04-08 08:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('questionnaire_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('questionnaire_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question_options_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_options', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('questions_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Retailers',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('retailer_id', models.AutoField(primary_key=True, serialize=False)),
                ('reatailer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('langitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.retailers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_file_name', models.CharField(default='avatar.png', max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('contact_number', models.CharField(max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.roles')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_submited', models.DateTimeField(default=datetime.datetime.now)),
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.areas')),
                ('brand', models.ManyToManyField(to='WebPortal.Brands')),
                ('category', models.ManyToManyField(to='WebPortal.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.country')),
                ('retaier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.retailers')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.stores')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyActivities',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('survey_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('langitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.surveys')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sku_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionStatments',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question_statment_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_statement', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questions')),
                ('question_options', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questionoptions')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.sku'),
        ),
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('questionnaire_id', models.AutoField(primary_key=True, serialize=False)),
                ('questionnaire_name', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questions')),
                ('questionnaire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questionnairetype')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.country'),
        ),
        migrations.AddField(
            model_name='brands',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.category'),
        ),
        migrations.AddField(
            model_name='areas',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.city'),
        ),
        migrations.AddField(
            model_name='areas',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.country'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questions')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questionnaires')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.surveys')),
            ],
        ),
    ]
