# Generated by Django 3.1.7 on 2021-04-13 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('area_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('langitude', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('city_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('langitude', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('country_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('langitude', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_submited', models.DateTimeField(default=datetime.datetime.now)),
                ('frequency', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.areas')),
                ('brand', models.ManyToManyField(to='WebPortal.Brands')),
                ('category', models.ManyToManyField(to='WebPortal.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.country')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('questionnaire_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question_options', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Retailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('reatailer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[('1', 'Admin'), ('2', 'User')], default=1, null=True)),
                ('profile_pic', models.CharField(default='avatar.png', max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('contact_number', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('langitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questionnaires')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('store_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('langitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.retailers')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sku_name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.category')),
            ],
            options={
                'verbose_name_plural': 'SKUs',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question_type', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.brands')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.sku')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='retaier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.retailers'),
        ),
        migrations.AddField(
            model_name='questionnaires',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.stores'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.country'),
        ),
        migrations.AddField(
            model_name='brands',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.category'),
        ),
        migrations.AddField(
            model_name='areas',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.city'),
        ),
        migrations.AddField(
            model_name='areas',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.country'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('answer', models.CharField(max_length=100)),
                ('Questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questionnaires')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.questions')),
            ],
        ),
    ]
