# Generated by Django 3.1.7 on 2021-04-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
